### ISSUE TITLE
Cannot find your emacs configuration using emacs-overlay in home-manager

### ISSUE THREAD

**Issue by zielOS** [bbigras/nix-config#13363]
Hi

I came across your github nix-config from this link you posted in nixos discourse https://discourse.nixos.org/t/how-to-use-the-emacs-overlay-with-home-manager-and-flakes/17261/3 .

I could not find the related emacs configuration in your repository. I also noticed you have doomDir with doom emacs files. Did you switch to doom emacs by any chance. I could not find the related nix file for that either. 

Could you help me out? It would be really appreciated. I am in a debian-based distro so I ended up installing home-manager and flake in the standalone form. I tried using the emacs-overlay example that used environment.systemPackages but I replaced that with home.packages. It installed everything but my configuration doesn't load properly.

**Comment by bbigras** [comment]
Hi!

I removed it since I was also testing doom-emacs.

I added it back. It's in the `try` branch for now (see https://github.com/bbigras/nix-config/commit/e96642f69f300114cdb00b01f7bb7b5515999dda (`users/bbigras/core/emacs/default.nix` might be a good start). I'll merge it in master as soon as it builds. If I didn't forget anything.

**Comment by bbigras** [comment]
Merged.

See:

https://github.com/bbigras/nix-config/tree/5de4cbf98b7c2685f0277b57457f57f6768742bd/users/bbigras/core/emacs

and

https://github.com/bbigras/nix-config/blob/5de4cbf98b7c2685f0277b57457f57f6768742bd/hosts/desktop/default.nix#L98-L102

I should check if nur is a flake now. Maybe I don't need to `nurNoPkgs = import nur { pkgs = null; nurpkgs = pkgs; };`.
